apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: canaryconfigs.fission.io
spec:
  conversion:
    strategy: None
  group: fission.io
  names:
    kind: CanaryConfig
    listKind: CanaryConfigList
    plural: canaryconfigs
    singular: canaryconfig
  preserveUnknownFields: true
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: false
  - name: v2
    served: true
    storage: true
status:
  acceptedNames:
    kind: CanaryConfig
    listKind: CanaryConfigList
    plural: canaryconfigs
    singular: canaryconfig
  storedVersions:
  - v2
