apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  generation: 1
  name: httptriggers.fission.io
  selfLink: /apis/apiextensions.k8s.io/v1/customresourcedefinitions/httptriggers.fission.io
spec:
  conversion:
    strategy: None
  group: fission.io
  names:
    kind: HTTPTrigger
    listKind: HTTPTriggerList
    plural: httptriggers
    singular: httptrigger
  preserveUnknownFields: true
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: false
  - name: v2
    served: true
    storage: true
status:
  acceptedNames:
    kind: HTTPTrigger
    listKind: HTTPTriggerList
    plural: httptriggers
    singular: httptrigger
  storedVersions:
  - v2
