apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  generation: 1
  name: kuberneteswatchtriggers.fission.io
  selfLink: /apis/apiextensions.k8s.io/v1/customresourcedefinitions/kuberneteswatchtriggers.fission.io
spec:
  conversion:
    strategy: None
  group: fission.io
  names:
    kind: KubernetesWatchTrigger
    listKind: KubernetesWatchTriggerList
    plural: kuberneteswatchtriggers
    singular: kuberneteswatchtrigger
  preserveUnknownFields: true
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: false
  - name: v2
    served: true
    storage: true
status:
  acceptedNames:
    kind: KubernetesWatchTrigger
    listKind: KubernetesWatchTriggerList
    plural: kuberneteswatchtriggers
    singular: kuberneteswatchtrigger
  storedVersions:
  - v2
